/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.magellanrx.auditions.test;

import org.junit.Test;

public class AuditionsControllerTest {
    @Test public void testSomeLibraryMethod() {
    	AuditionsControllerTest classUnderTest = new AuditionsControllerTest();
        //assertTrue("someMethod should return 'true'", classUnderTest.someMethod());
    }
}
